// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenantRouter.Data;

#nullable disable

namespace TenantRouter.Data.Migrations
{
    [DbContext(typeof(TenantRouterDbContext))]
    [Migration("20260819013739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenantRouter.Tenants.Subdomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ServerUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("subdomains", (string)null);
                });

            modelBuilder.Entity("TenantRouter.Tenants.TenantUsername", b =>
                {
                    b.Property<int>("SubdomainId")
                        .HasColumnType("integer");

                    b.Property<string>("UsernameHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("SubdomainId", "UsernameHash");

                    b.HasIndex("UsernameHash");

                    b.ToTable("tenant_usernames", (string)null);
                });

            modelBuilder.Entity("TenantRouter.Tenants.TenantUsername", b =>
                {
                    b.HasOne("TenantRouter.Tenants.Subdomain", "Subdomain")
                        .WithMany()
                        .HasForeignKey("SubdomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subdomain");
                });
#pragma warning restore 612, 618
        }
    }
}
