// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenantRouter.Data;

#nullable disable

namespace TenantRouter.Data.Migrations
{
    [DbContext(typeof(TenantRouterDbContext))]
    partial class TenantRouterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenantRouter.Tenants.Subdomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientOrigin")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("client_origin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("ServerUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("server_url");

                    b.HasKey("Id")
                        .HasName("pk_subdomains");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subdomains_name");

                    b.ToTable("subdomains", (string)null);
                });

            modelBuilder.Entity("TenantRouter.Tenants.TenantUsername", b =>
                {
                    b.Property<int>("SubdomainId")
                        .HasColumnType("integer")
                        .HasColumnName("subdomain_id");

                    b.Property<string>("UsernameHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("username_hash");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("SubdomainId", "UsernameHash")
                        .HasName("pk_tenant_usernames");

                    b.HasIndex("UsernameHash")
                        .HasDatabaseName("ix_tenant_usernames_username_hash");

                    b.ToTable("tenant_usernames", (string)null);
                });

            modelBuilder.Entity("TenantRouter.Tenants.TenantUsername", b =>
                {
                    b.HasOne("TenantRouter.Tenants.Subdomain", "Subdomain")
                        .WithMany()
                        .HasForeignKey("SubdomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_usernames_subdomains_subdomain_id");

                    b.Navigation("Subdomain");
                });
#pragma warning restore 612, 618
        }
    }
}
