// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatientPortalServer.Data;

#nullable disable

namespace PatientPortalServer.Data.Migrations
{
    [DbContext(typeof(PatientPortalDbContext))]
    partial class PatientPortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatientPortalServer.Tenants.TenantUsername", b =>
                {
                    b.Property<string>("Subdomain")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UsernameHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Subdomain", "UsernameHash");

                    b.HasIndex("UsernameHash");

                    b.ToTable("tenant_usernames", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
